# SPDX-License-Identifier: GPL-2.0

#dtb-$(CONFIG_ARCH_R9A07G044) += r9a07g044c2-smarc.dtb
dtb-$(CONFIG_ARCH_R9A07G044) += r9a07g044l2-smarc.dtb \
				myb-rzg2l-disp.dtb \
				myb-rzg2l-lvdshdmi.dtb
dtb-$(CONFIG_ARCH_R9A07G044) += r9a07g044l2-dev.dtb
